main = "hello"

[[graphs]]
name = "hello"
connections = [
	{ cap=16, ports=["server:inp", "hello:out"] },
	{ cap=16, ports=["server:out", "hello:inp"] }
]

        [[graphs.nodes]]
        name = "server"
        ty = "ImageServer"
        port = 9001 # int, the port on which server will listen
        response = "json" # json | image, which means response format

        [[graphs.nodes]]
        name = "hello"
        ty = "Hello"
        arch = "resnet18"
        model_file = "/home/security/demo/config/model"
        weight_file = "/root/resnet/output/resnet18-t/checkpoint.pkl"
